### ISSUE TITLE
empty welcome email, confirmation instructions

### ISSUE THREAD

**Issue by tilfischer** [ComPlat/chemotion_REPO#74] opened 2024-03-04 09:34 UTC
- I am an ELN system admin and user

# Description
When signing up, users receive an welcome message via email with the subject "Welcome to Chemotion Repository." However, the email does not have any content. This is irritating to users. Another email is also sent to the user to confirm the registration.

Bot emails should be merged. Moreover, the confirmation email could be more pretty and at least should contain a link to the documentation. 

Best,
Tillmann

**Comment by cllde8** [comment] 2024-03-13 09:14
Hi @tilfischer 

Thank you for bringing this to our attention. We have reviewed the configuration and made some adjustments to the email content. Typically, the user should receive the confirmation email after creating a new account. Once confirmed, the welcome email is sent to the user, containing pertinent information.

The following screenshots are provided for your reference. We appreciate your help in improving the platform.

- **Confirmation**

![screenshot-navigator gmx net-2024 03 12-21_53_18-1](https://github.com/ComPlat/chemotion_REPO/assets/42910431/1ba19a42-6476-43df-b0d7-67df53739697)


- **Welcome**

![screenshot-navigator gmx net-2024 03 12-21_53_47](https://github.com/ComPlat/chemotion_REPO/assets/42910431/722d50ce-cb72-407a-91b2-43adff69ca15)


Best regards,
Claire

**Comment by tilfischer** [comment] 2024-03-13 10:43
Thank you! I registered with a test account and received the email to confirm my account. After confirmation via the link provided in that email I received, to my surprise, two welcome emails with identical content.

**Comment by cllde8** [comment] 2024-03-14 22:55
Hi @tilfischer 

I tried to replicate the issue you encountered, but everything seems to be functioning correctly from my end. Upon registering for an account, I promptly received a confirmation email, followed by a welcome email upon completion of the confirmation process. Could you please try using the function again to see if the problem persists on your end?

Best regards,
Claire

**Comment by tilfischer** [comment] 2024-03-15 09:19
I signed up again and received the email to confirm the account. I confirmed and received one welcome email. Interesting. I actually tested this twice before reporting the two welcome emails...  From my end, this seems to be done. You are welcome to close this issue.

**Comment by tilfischer** [comment] 2024-03-15 11:35
Seems to depend on the client. Example from my mobile: 

![IMG_1547](https://github.com/ComPlat/chemotion_REPO/assets/85482437/12b87500-e50f-429a-8e90-d3104d4106d0)

Outlook seems to use Outlooks default font. 

Best,
Tillmann

**Comment by cllde8** [comment] 2024-03-19 09:00
Hi @tilfischer 

Thank you for confirming the resolution of the email issue. We are proceeding to close this ticket. Regarding the font, we tend to use the email client's settings (as you observed 🙂), as individuals often prefer to read emails according to their personal preferences.

Best regards,
Claire

**Closed** 2024-03-19 11:49 UTC
